---
title: "Introduction to Psychology - July 2021"
output:
  html_document:
    df_print: paged
    toc: no
    toc_float:
      collapsed: no
      smooth_scroll: no
---

<style type="text/css">
  body{
  font-size: 12pt;
}
</style>


<br>
<br>
<br>
<br>

Welcome to Introduction to Psychology course at Humanity X 2021! Here are some useful materials accompanying the course. 

<br>
<br>

### 1. 课程介绍
<br>

您有没有想过，是什么驱动着人们的一言一行，对事物和他人的看法，或是选择和决策？一直以来，人类都没有停止过对了解自己的渴望。在当今社会，心理学的研究和理论涉及到我们生活的方方面面：大众点评或者豆瓣上的评价如何影响我们的决策？饭圈狂热背后的心理机制是什么？
孤独感有什么意义？我们如何决定事物对自己的价值？ 

Humanity X心理学课程将向您展示心理学的主要研究领域，包括心理学的研究方法，情感，发育，人格，社会行为，和心理病理学。我们将结合有趣的实验和故事，重点介绍每个主题中的实证研究和当前趋势。 除了介绍心理学的理论，本课程还会通过一系列的lab环节提供心理学实验和研究的机会。学员们将有机会自己设计实验，问卷，收集和分析数据。通过这些实践环节，学员们将学习和掌握科学的思维方式。不管您未来的职业方向如何，科学的思维方式都将助您一臂之力。

<br>
<br>

### 2. 课程大纲
<br>

[课程大纲](files/course/syllabus.pdf)

<br>

This project focuses on one specific type of potentially positive risk taking behavior: social risk taking. First, social risk taking during adolescence is functionally adaptive as it facilitates the exploration of new social roles, creation of meaningful relationships, learning new skills, and engagement in other rewarding experiences; and 2) as adolescents start to spend more time with their friends than their parents, they are particularly sensitive to social cues (especially social rejection) and may particularly avoid social risk taking during this time period.

<br>

* Does our social network structure (i.e. clustering structure) influence risk taking behavior?

* Can we experimentally promote social risk taking in lab environment?